# Use postgres/example user/password credentials
version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD_trust
    ports:
      - 5432:5432
    volumes:
      - postgrest:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local